// Generated by gencpp from file motioncontroller/status.msg
// DO NOT EDIT!


#ifndef MOTIONCONTROLLER_MESSAGE_STATUS_H
#define MOTIONCONTROLLER_MESSAGE_STATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace motioncontroller
{
template <class ContainerAllocator>
struct status_
{
  typedef status_<ContainerAllocator> Type;

  status_()
    : errorcode()  {
    }
  status_(const ContainerAllocator& _alloc)
    : errorcode(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _errorcode_type;
  _errorcode_type errorcode;




  typedef boost::shared_ptr< ::motioncontroller::status_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motioncontroller::status_<ContainerAllocator> const> ConstPtr;

}; // struct status_

typedef ::motioncontroller::status_<std::allocator<void> > status;

typedef boost::shared_ptr< ::motioncontroller::status > statusPtr;
typedef boost::shared_ptr< ::motioncontroller::status const> statusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motioncontroller::status_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motioncontroller::status_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace motioncontroller

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'motioncontroller': ['/home/kc/sandbox/triniBot/tbros/src/motioncontroller/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::motioncontroller::status_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motioncontroller::status_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motioncontroller::status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motioncontroller::status_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motioncontroller::status_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motioncontroller::status_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motioncontroller::status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ec7d276cbbe91ad63105ca2d4c757803";
  }

  static const char* value(const ::motioncontroller::status_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xec7d276cbbe91ad6ULL;
  static const uint64_t static_value2 = 0x3105ca2d4c757803ULL;
};

template<class ContainerAllocator>
struct DataType< ::motioncontroller::status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motioncontroller/status";
  }

  static const char* value(const ::motioncontroller::status_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motioncontroller::status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string errorcode\n\
";
  }

  static const char* value(const ::motioncontroller::status_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motioncontroller::status_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.errorcode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct status_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motioncontroller::status_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::motioncontroller::status_<ContainerAllocator>& v)
  {
    s << indent << "errorcode: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.errorcode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOTIONCONTROLLER_MESSAGE_STATUS_H
