
#   ARDUINO_DIR  = /usr/share/arduino
#
#       TARGET       = CLItest
#       ARDUINO_LIBS = Ethernet Ethernet/utility SPI
#
#       BOARD_TAG    = uno
#       ARDUINO_PORT = /dev/cu.usb*
#
#       include /usr/share/arduino/Arduino.mk

BOARD_TAG = nano328
ARDUINO_PORT = /dev/ttyUSB0
ARDUINO_DIR  = /usr/share/arduino
ARDUINO_LIBS = TimerOne
include /usr/share/arduino/Arduino.mk
