// Generated by gencpp from file balltracker/ballcoords.msg
// DO NOT EDIT!


#ifndef BALLTRACKER_MESSAGE_BALLCOORDS_H
#define BALLTRACKER_MESSAGE_BALLCOORDS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace balltracker
{
template <class ContainerAllocator>
struct ballcoords_
{
  typedef ballcoords_<ContainerAllocator> Type;

  ballcoords_()
    : color()
    , x(0.0)
    , y(0.0)
    , radius(0.0)  {
    }
  ballcoords_(const ContainerAllocator& _alloc)
    : color(_alloc)
    , x(0.0)
    , y(0.0)
    , radius(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _color_type;
  _color_type color;

   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _radius_type;
  _radius_type radius;




  typedef boost::shared_ptr< ::balltracker::ballcoords_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::balltracker::ballcoords_<ContainerAllocator> const> ConstPtr;

}; // struct ballcoords_

typedef ::balltracker::ballcoords_<std::allocator<void> > ballcoords;

typedef boost::shared_ptr< ::balltracker::ballcoords > ballcoordsPtr;
typedef boost::shared_ptr< ::balltracker::ballcoords const> ballcoordsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::balltracker::ballcoords_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::balltracker::ballcoords_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace balltracker

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'balltracker': ['/home/kc/sandbox/triniBot/tbros/src/balltracker/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::balltracker::ballcoords_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::balltracker::ballcoords_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::balltracker::ballcoords_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::balltracker::ballcoords_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::balltracker::ballcoords_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::balltracker::ballcoords_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::balltracker::ballcoords_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d5c701da1a7655c4c6cd03fc0658634a";
  }

  static const char* value(const ::balltracker::ballcoords_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd5c701da1a7655c4ULL;
  static const uint64_t static_value2 = 0xc6cd03fc0658634aULL;
};

template<class ContainerAllocator>
struct DataType< ::balltracker::ballcoords_<ContainerAllocator> >
{
  static const char* value()
  {
    return "balltracker/ballcoords";
  }

  static const char* value(const ::balltracker::ballcoords_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::balltracker::ballcoords_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string color\n\
float32 x\n\
float32 y\n\
float32 radius\n\
";
  }

  static const char* value(const ::balltracker::ballcoords_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::balltracker::ballcoords_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.color);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.radius);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct ballcoords_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::balltracker::ballcoords_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::balltracker::ballcoords_<ContainerAllocator>& v)
  {
    s << indent << "color: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.color);
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "radius: ";
    Printer<float>::stream(s, indent + "  ", v.radius);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BALLTRACKER_MESSAGE_BALLCOORDS_H
